### ISSUE TITLE
Add support for `discard_empty`

### ISSUE THREAD

**Issue by epaune-k** [am-kantox/dry-mutations#3]
One of the options available in mutation gem for string is to define it as `discard_empty: true`. But this option is not available with dry-mutations...

**Comment by am-kantox** [comment]
There is no problem to implement this, but I doubt I understand why is it needed. I always used to say that the most destructive and damn thing Rails brought to Ruby world is `try` method, that literally allows a developer to not understand what’s going on under the hood.

This `discard_empty` is the same. Why it would be a responsibility of `schema` (!) to convert empty arrays and strings to `nil`s and silently drop them from the input? Should not the developer take care about what’s passed to the method? BTW, in the real world empty array and nothing are completely different things.

Please clarify: what exact usecase do you need this for?

**Comment by epaune-k** [comment]
The use case is supporting legacy mutations, of course. The less changes needed on existing mutations, the better. Otherwise the adoption of dry-mutations require more work.

Mutations are used to process data coming from forms, where usually optional fields are present. Data from these fields arrives as empty strings, so the `discard_empty: true` is handy for cleaning them up.
